// src/renderer/src/App.jsx
import React, { useState, useRef, useEffect, useCallback } from 'react'
import TitleBar from './components/TitleBar'
import Playlist from './components/Playlist'
import Spectrum from './components/Spectrum'
import Controls from './components/Controls'
import SettingsModal from './components/SettingsModal'
import AboutModal from './components/AboutModal'
import { LANG, makeT } from './i18n'

let _id = 0

const REPEAT = { NONE: 'none', ALL: 'all', ONE: 'one' }
const AUDIO_RE = /\.(mp3|flac|ogg|wav|aac|m4a|opus|wma)$/i
const SETTINGS_KEY = 'retroamp:settings:v1'
const DEFAULT_SETTINGS = {
  theme: 'matrix',
  language: LANG.RU,
  showCover: true,
  autoPlayOnAdd: true,
  compactMode: false,
  vizIntensity: 1,
  vizMode: 'bars',
}

function makeTrack(filePath, meta = {}) {
  const sep = filePath.includes('\\') ? '\\' : '/'
  const name = filePath.split(sep).pop() || filePath
  const parent = filePath.split(sep).slice(-2, -1)[0] || ''
  const title = meta.title || name
    .replace(/\.[^.]+$/, '')
    .replace(/^\d+[\s._-]+/, '')
    .replace(/[_]/g, ' ')
  const artist = typeof meta.artist === 'string' ? meta.artist.trim() : ''
  const album = typeof meta.album === 'string' && meta.album.trim() ? meta.album.trim() : parent
  return {
    id: ++_id,
    path: filePath,
    name,
    title,
    artist,
    album,
    year: meta.year || '',
    cover: meta.cover || null,
    duration: Number.isFinite(meta.duration) ? meta.duration : 0,
  }
}

function loadSettings() {
  try {
    const parsed = JSON.parse(localStorage.getItem(SETTINGS_KEY) || '{}')
    return { ...DEFAULT_SETTINGS, ...parsed }
  } catch {
    return { ...DEFAULT_SETTINGS }
  }
}

export function fmtTime(sec) {
  if (!isFinite(sec) || sec < 0) return '--:--'
  const m = Math.floor(sec / 60)
  const s = Math.floor(sec % 60)
  return `${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')}`
}

export default function App() {
  const [tracks, setTracks] = useState([])
  const [currentIdx, setCurrentIdx] = useState(-1)
  const [playing, setPlaying] = useState(false)
  const [currentTime, setCurrentTime] = useState(0)
  const [duration, setDuration] = useState(0)
  const [volume, setVolume] = useState(0.8)
  const [muted, setMuted] = useState(false)
  const [repeat, setRepeat] = useState(REPEAT.NONE)
  const [shuffle, setShuffle] = useState(false)
  const [dragOver, setDragOver] = useState(false)
  const [showSettings, setShowSettings] = useState(false)
  const [showAbout, setShowAbout] = useState(false)
  const [vizMenu, setVizMenu] = useState({ visible: false, x: 0, y: 0 })
  const [settings, setSettings] = useState(loadSettings)
  const t = makeT(settings.language)

  useEffect(() => {
    document.documentElement.lang = settings.language
  }, [settings.language])

  const tracksRef = useRef(tracks)
  const currentIdxRef = useRef(currentIdx)
  const repeatRef = useRef(repeat)
  const shuffleRef = useRef(shuffle)
  useEffect(() => { tracksRef.current = tracks }, [tracks])
  useEffect(() => { currentIdxRef.current = currentIdx }, [currentIdx])
  useEffect(() => { repeatRef.current = repeat }, [repeat])
  useEffect(() => { shuffleRef.current = shuffle }, [shuffle])

  useEffect(() => {
    localStorage.setItem(SETTINGS_KEY, JSON.stringify(settings))
  }, [settings])

  useEffect(() => {
    window.electronAPI.setCompactMode?.(!!settings.compactMode)
  }, [settings.compactMode])

  useEffect(() => {
    const close = () => setVizMenu((m) => ({ ...m, visible: false }))
    window.addEventListener('click', close)
    return () => window.removeEventListener('click', close)
  }, [])

  const audioRef = useRef(null)
  const ctxRef = useRef(null)
  const analyserRef = useRef(null)

  const handleEnded = useCallback(() => {
    const tl = tracksRef.current
    const ci = currentIdxRef.current
    const rep = repeatRef.current
    const sh = shuffleRef.current
    if (rep === REPEAT.ONE && audioRef.current) {
      audioRef.current.currentTime = 0
      audioRef.current.play().catch(() => {})
      return
    }
    let next
    if (sh) {
      next = Math.floor(Math.random() * tl.length)
    } else {
      next = ci + 1
      if (next >= tl.length) {
        if (rep === REPEAT.ALL) next = 0
        else { setPlaying(false); return }
      }
    }
    if (next >= 0 && tl[next]) playAt(next)
  }, [])

  useEffect(() => {
    const audio = new Audio()
    audioRef.current = audio
    audio.preload = 'auto'
    audio.crossOrigin = 'anonymous'
    audio.volume = volume

    const Ctor = window.AudioContext || window.webkitAudioContext
    const ctx = new Ctor()
    const analyser = ctx.createAnalyser()
    analyser.fftSize = 1024
    analyser.smoothingTimeConstant = 0.8
    const src = ctx.createMediaElementSource(audio)
    src.connect(analyser)
    analyser.connect(ctx.destination)
    ctxRef.current = ctx
    analyserRef.current = analyser

    const onTime = () => setCurrentTime(audio.currentTime)
    const onMeta = () => setDuration(audio.duration)
    const onPlay = () => setPlaying(true)
    const onPause = () => setPlaying(false)
    const onEnded = () => handleEnded()

    audio.addEventListener('timeupdate', onTime)
    audio.addEventListener('loadedmetadata', onMeta)
    audio.addEventListener('play', onPlay)
    audio.addEventListener('pause', onPause)
    audio.addEventListener('ended', onEnded)

    audio.addEventListener('loadedmetadata', () => {
      const idx = currentIdxRef.current
      if (idx < 0) return
      setTracks((prev) => {
        const copy = [...prev]
        if (copy[idx]) copy[idx] = { ...copy[idx], duration: audio.duration }
        return copy
      })
    })

    return () => {
      audio.removeEventListener('timeupdate', onTime)
      audio.removeEventListener('loadedmetadata', onMeta)
      audio.removeEventListener('play', onPlay)
      audio.removeEventListener('pause', onPause)
      audio.removeEventListener('ended', onEnded)
      audio.pause()
      if (src) src.disconnect()
      analyser.disconnect()
      ctx.close()
    }
  }, [handleEnded])

  useEffect(() => {
    if (audioRef.current) {
      audioRef.current.volume = volume
      audioRef.current.muted = muted
    }
  }, [volume, muted])

  const playAt = useCallback(async (idx, list) => {
    const tl = list ?? tracksRef.current
    const track = tl[idx]
    if (!track) return
    const audio = audioRef.current
    if (!audio) return
    if (ctxRef.current?.state === 'suspended') ctxRef.current.resume()

    const fileUrl = await window.electronAPI.toFileUrl(track.path)
    if (!fileUrl) return

    audio.src = fileUrl
    audio.load()
    audio.play().catch(console.error)
    setCurrentIdx(idx)
    setCurrentTime(0)
    setDuration(0)
  }, [])

  const togglePlay = useCallback(() => {
    const audio = audioRef.current
    if (!audio) return
    if (ctxRef.current?.state === 'suspended') ctxRef.current.resume()
    if (playing) {
      audio.pause()
    } else {
      if (tracks.length === 0) return
      if (!audio.src) { playAt(0); return }
      audio.play().catch(console.error)
    }
  }, [playing, tracks.length, playAt])

  const playNext = useCallback(() => {
    const tl = tracksRef.current
    if (tl.length === 0) return
    const next = shuffleRef.current
      ? Math.floor(Math.random() * tl.length)
      : (currentIdxRef.current + 1) % tl.length
    playAt(next)
  }, [playAt])

  const playPrev = useCallback(() => {
    const audio = audioRef.current
    const tl = tracksRef.current
    if (tl.length === 0) return
    if (audio && audio.currentTime > 3) {
      audio.currentTime = 0
      return
    }
    const prev = shuffleRef.current
      ? Math.floor(Math.random() * tl.length)
      : (currentIdxRef.current - 1 + tl.length) % tl.length
    playAt(prev)
  }, [playAt])

  const stop = useCallback(() => {
    const audio = audioRef.current
    if (!audio) return
    audio.pause()
    audio.currentTime = 0
  }, [])

  const seek = useCallback((ratio) => {
    const audio = audioRef.current
    if (audio && isFinite(audio.duration)) {
      audio.currentTime = ratio * audio.duration
    }
  }, [])

  const addPaths = useCallback(async (paths) => {
    const filtered = (paths || []).filter((p) => AUDIO_RE.test(p))
    if (!filtered.length) return
    let metadata = []
    try {
      metadata = await window.electronAPI.readTags(filtered)
    } catch {
      metadata = []
    }
    const metaMap = new Map(metadata.map((m) => [m.path, m]))
    const newTracks = filtered.map((p) => makeTrack(p, metaMap.get(p) || {}))

    setTracks((prev) => {
      const merged = [...prev, ...newTracks]
      if (prev.length === 0 && newTracks.length > 0 && settings.autoPlayOnAdd) {
        setTimeout(() => playAt(0, merged), 50)
      }
      return merged
    })
  }, [playAt, settings.autoPlayOnAdd])

  const clearPlaylist = useCallback(() => {
    audioRef.current?.pause()
    setTracks([])
    setCurrentIdx(-1)
    setPlaying(false)
    setCurrentTime(0)
    setDuration(0)
  }, [])

  const removeTrack = useCallback((idx) => {
    setTracks((prev) => {
      const arr = prev.filter((_, i) => i !== idx)
      setCurrentIdx((ci) => {
        if (ci === idx) {
          audioRef.current?.pause()
          if (arr.length === 0) return -1
          const ni = Math.min(idx, arr.length - 1)
          setTimeout(() => playAt(ni, arr), 0)
          return ni
        }
        return ci > idx ? ci - 1 : ci
      })
      return arr
    })
  }, [playAt])

  const reorderTracks = useCallback((fromIdx, toIdx) => {
    if (fromIdx === toIdx) return
    setTracks((prev) => {
      const arr = [...prev]
      const [moved] = arr.splice(fromIdx, 1)
      arr.splice(toIdx, 0, moved)
      setCurrentIdx((ci) => {
        if (ci === fromIdx) return toIdx
        if (fromIdx < ci && ci <= toIdx) return ci - 1
        if (toIdx <= ci && ci < fromIdx) return ci + 1
        return ci
      })
      return arr
    })
  }, [])

  const handleOpenFiles = useCallback(async () => {
    const paths = await window.electronAPI.openFiles()
    if (paths.length) addPaths(paths)
  }, [addPaths])

  const handleOpenFolder = useCallback(async () => {
    const paths = await window.electronAPI.openFolder()
    if (paths.length) addPaths(paths)
  }, [addPaths])

  const handleImportM3U = useCallback(async () => {
    const paths = await window.electronAPI.importM3U()
    if (paths.length) addPaths(paths)
  }, [addPaths])

  const handleExportM3U = useCallback(async () => {
    if (!tracksRef.current.length) return
    await window.electronAPI.exportM3U({ tracks: tracksRef.current })
  }, [])

  const onDragOver = (e) => { e.preventDefault(); setDragOver(true) }
  const onDragLeave = (e) => { if (!e.currentTarget.contains(e.relatedTarget)) setDragOver(false) }
  const onDrop = useCallback((e) => {
    e.preventDefault()
    setDragOver(false)
    const paths = []
    for (const file of e.dataTransfer.files) {
      if (file.path && AUDIO_RE.test(file.path)) paths.push(file.path)
    }
    if (paths.length) addPaths(paths)
  }, [addPaths])

  const onSpectrumContextMenu = useCallback((e) => {
    e.preventDefault()
    setVizMenu({ visible: true, x: e.clientX, y: e.clientY })
  }, [])

  const setVizMode = useCallback((mode) => {
    setSettings((prev) => ({ ...prev, vizMode: mode }))
    setVizMenu((m) => ({ ...m, visible: false }))
  }, [])

  useEffect(() => {
    const onKey = (e) => {
      if (e.target.tagName === 'INPUT' || e.target.tagName === 'SELECT') return
      switch (e.code) {
        case 'Space':
          e.preventDefault(); togglePlay(); break
        case 'ArrowRight':
          if (e.ctrlKey) { e.preventDefault(); playNext() }
          else if (audioRef.current) audioRef.current.currentTime = Math.min(duration, currentTime + 5)
          break
        case 'ArrowLeft':
          if (e.ctrlKey) { e.preventDefault(); playPrev() }
          else if (audioRef.current) audioRef.current.currentTime = Math.max(0, currentTime - 5)
          break
        case 'ArrowUp':
          e.preventDefault(); setVolume((v) => Math.min(1, parseFloat((v + 0.05).toFixed(2)))); break
        case 'ArrowDown':
          e.preventDefault(); setVolume((v) => Math.max(0, parseFloat((v - 0.05).toFixed(2)))); break
        case 'KeyM':
          setMuted((m) => !m); break
        case 'KeyS':
          if (e.ctrlKey) { e.preventDefault(); stop() }
          break
        case 'Comma':
          if (e.ctrlKey) { e.preventDefault(); setShowSettings(true) }
          break
        default:
          break
      }
    }
    window.addEventListener('keydown', onKey)
    return () => window.removeEventListener('keydown', onKey)
  }, [togglePlay, playNext, playPrev, stop, currentTime, duration])

  const currentTrack = tracks[currentIdx] ?? null
  const currentArtist = currentTrack?.artist || t('unknownArtist')
  const currentAlbum = currentTrack?.album || t('unknownAlbum')
  const currentYear = currentTrack?.year ? String(currentTrack.year) : null

  return (
    <div
      className={`app theme-${settings.theme}${settings.compactMode ? ' app--compact' : ''}${dragOver ? ' app--dragover' : ''}`}
      onDragOver={onDragOver}
      onDragLeave={onDragLeave}
      onDrop={onDrop}
    >
      <TitleBar
        track={currentTrack}
        t={t}
        onOpenFiles={handleOpenFiles}
        onOpenFolder={handleOpenFolder}
        onImportM3U={handleImportM3U}
        onExportM3U={handleExportM3U}
        onOpenSettings={() => setShowSettings(true)}
        onToggleCompact={() => setSettings((prev) => ({ ...prev, compactMode: !prev.compactMode }))}
        compactMode={!!settings.compactMode}
        onOpenAbout={() => setShowAbout(true)}
        onClear={clearPlaylist}
      />

      <div className="main-area">
        <Playlist
          tracks={tracks}
          t={t}
          currentIdx={currentIdx}
          playing={playing}
          onSelect={playAt}
          onReorder={reorderTracks}
          onRemove={removeTrack}
          onAddFiles={handleOpenFiles}
          onAddFolder={handleOpenFolder}
        />

        <div className="right-panel">
          <Spectrum
            analyserRef={analyserRef}
            playing={playing}
            intensity={settings.vizIntensity}
            mode={settings.vizMode}
            onContextMenu={onSpectrumContextMenu}
          />

          <div className="track-meta">
            {settings.showCover && (
              <div className="track-meta__cover-wrap">
                {currentTrack?.cover ? (
                  <img src={currentTrack.cover} alt="Album cover" className="track-meta__cover" />
                ) : (
                  <div className="track-meta__cover track-meta__cover--fallback">{t('noCover')}</div>
                )}
              </div>
            )}

            <div className="track-info">
              <span className="track-info__label">{t('nowPlaying')}</span>
              <span className="track-info__title">
                {currentTrack ? currentTrack.title : t('noTrackLoaded')}
              </span>
              {currentTrack ? (
                <div className="track-info__meta">
                  <span className="track-info__sub">{`${t('metaArtist')}: ${currentArtist}`}</span>
                  <span className="track-info__sub">{`${t('metaAlbum')}: ${currentAlbum}${currentYear ? ` (${currentYear})` : ''}`}</span>
                </div>
              ) : (
                <span className="track-info__sub">{t('dropHint')}</span>
              )}
            </div>
          </div>
        </div>
      </div>

      <Controls
        playing={playing}
        currentTime={currentTime}
        duration={duration}
        volume={volume}
        muted={muted}
        repeat={repeat}
        t={t}
        shuffle={shuffle}
        hasTracks={tracks.length > 0}
        trackCount={tracks.length}
        currentIdx={currentIdx}
        onTogglePlay={togglePlay}
        onNext={playNext}
        onPrev={playPrev}
        onStop={stop}
        onSeek={seek}
        onVolume={setVolume}
        onMute={() => setMuted((m) => !m)}
        onRepeat={() => setRepeat((r) => (r === REPEAT.NONE ? REPEAT.ALL : r === REPEAT.ALL ? REPEAT.ONE : REPEAT.NONE))}
        onShuffle={() => setShuffle((s) => !s)}
      />

      {dragOver && (
        <div className="drop-overlay">
          <div className="drop-overlay__inner">{t('dropOverlay')}</div>
        </div>
      )}

      {vizMenu.visible && (
        <div
          className="playlist__ctx viz__ctx"
          style={{ left: `${vizMenu.x}px`, top: `${vizMenu.y}px` }}
          onClick={(e) => e.stopPropagation()}
          onContextMenu={(e) => e.preventDefault()}
        >
          <div className="viz__ctx-title">{t('vizMenuTitle')}</div>
          <button
            className={settings.vizMode === 'bars' ? 'menu-item menu-item--active' : 'menu-item'}
            onClick={() => setVizMode('bars')}
          >
            {t('vizBars')}
          </button>
          <button
            className={settings.vizMode === 'dots' ? 'menu-item menu-item--active' : 'menu-item'}
            onClick={() => setVizMode('dots')}
          >
            {t('vizDots')}
          </button>
          <button
            className={settings.vizMode === 'mirror' ? 'menu-item menu-item--active' : 'menu-item'}
            onClick={() => setVizMode('mirror')}
          >
            {t('vizMirror')}
          </button>
        </div>
      )}

      {showSettings && (
        <SettingsModal
          settings={settings}
          t={t}
          onChange={setSettings}
          onClose={() => setShowSettings(false)}
        />
      )}

      {showAbout && (
        <AboutModal
          t={t}
          onClose={() => setShowAbout(false)}
        />
      )}
    </div>
  )
}

// src/renderer/src/App.vue
<script setup>
import { computed, onBeforeUnmount, onMounted, ref, watch } from 'vue'

const AUDIO_RE = /\.(mp3|flac|ogg|wav|aac|m4a|opus|wma)$/i
const SETTINGS_KEY = 'retroamp:settings:v1'
const DEFAULT_SETTINGS = {
  compactMode: false,
  showCover: true,
  autoPlayOnAdd: true,
  vizIntensity: 1,
}
let nextId = 1

const tracks = ref([])
const currentIdx = ref(-1)
const playing = ref(false)
const currentTime = ref(0)
const duration = ref(0)
const volume = ref(0.8)
const muted = ref(false)
const settings = ref(loadSettings())
const showSettings = ref(false)
const dragOver = ref(false)
const compact = computed(() => !!settings.value.compactMode)

const canvasRef = ref(null)
let rafId = null
let audio = null
let audioCtx = null
let analyser = null
let sourceNode = null

const currentTrack = computed(() => tracks.value[currentIdx.value] ?? null)

function loadSettings() {
  try {
    return { ...DEFAULT_SETTINGS, ...(JSON.parse(localStorage.getItem(SETTINGS_KEY) || '{}')) }
  } catch {
    return { ...DEFAULT_SETTINGS }
  }
}

function fmtTime(sec) {
  if (!Number.isFinite(sec) || sec < 0) return '--:--'
  const m = Math.floor(sec / 60)
  const s = Math.floor(sec % 60)
  return `${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')}`
}

function fileNameFromPath(filePath) {
  const sep = filePath.includes('\\') ? '\\' : '/'
  return filePath.split(sep).pop() || filePath
}

function parentNameFromPath(filePath) {
  const sep = filePath.includes('\\') ? '\\' : '/'
  const chunks = filePath.split(sep)
  return chunks.length > 1 ? (chunks[chunks.length - 2] || '') : ''
}

function makeTrack(filePath, meta = {}) {
  const name = fileNameFromPath(filePath)
  const title = (meta.title || name)
    .replace(/\.[^.]+$/, '')
    .replace(/^\d+[\s._-]+/, '')
    .replace(/[_]/g, ' ')
  const artist = typeof meta.artist === 'string' ? meta.artist.trim() : ''
  const album = typeof meta.album === 'string' && meta.album.trim() ? meta.album.trim() : parentNameFromPath(filePath)

  return {
    id: nextId++,
    path: filePath,
    name,
    title,
    artist,
    album,
    year: meta.year || '',
    duration: Number.isFinite(meta.duration) ? meta.duration : 0,
    cover: meta.cover || null,
  }
}

async function loadCoverForTrack(track) {
  if (!track || track.cover || !settings.value.showCover) return
  try {
    const cover = await window.electronAPI.readCover(track.path)
    if (!cover) return
    tracks.value = tracks.value.map((item) => (item.id === track.id ? { ...item, cover } : item))
  } catch {
    // ignore cover read errors
  }
}

async function addPaths(paths) {
  const filtered = (paths || []).filter((item) => AUDIO_RE.test(item))
  if (!filtered.length) return

  let metadata = []
  try {
    metadata = await window.electronAPI.readTags(filtered)
  } catch {
    metadata = []
  }

  const brokenBatch =
    metadata.length !== filtered.length ||
    metadata.every((item) => !item?.title && !item?.artist && !item?.album)

  if (brokenBatch) {
    metadata = await Promise.all(
      filtered.map(async (filePath) => {
        try {
          const single = await window.electronAPI.readTags([filePath])
          return Array.isArray(single) && single[0] ? single[0] : { path: filePath }
        } catch {
          return { path: filePath }
        }
      })
    )
  }

  const map = new Map(metadata.map((item) => [item.path, item]))
  const appended = filtered.map((filePath) => makeTrack(filePath, map.get(filePath) || {}))
  const wasEmpty = tracks.value.length === 0
  tracks.value = [...tracks.value, ...appended]

  if (wasEmpty && appended.length > 0 && settings.value.autoPlayOnAdd) {
    await playAt(0)
  }
}

async function importM3U() {
  const paths = await window.electronAPI.importM3U()
  await addPaths(paths)
}

async function exportM3U() {
  await window.electronAPI.exportM3U(tracks.value)
}

function openSettings() {
  showSettings.value = true
}

function closeSettings() {
  showSettings.value = false
}

async function openFiles() {
  const paths = await window.electronAPI.openFiles()
  await addPaths(paths)
}

async function openFolder() {
  const paths = await window.electronAPI.openFolder()
  await addPaths(paths)
}

async function playAt(idx) {
  const track = tracks.value[idx]
  if (!track || !audio) return
  if (audioCtx && audioCtx.state === 'suspended') await audioCtx.resume()

  const fileUrl = await window.electronAPI.toFileUrl(track.path)
  if (!fileUrl) return

  audio.src = fileUrl
  audio.load()
  await audio.play().catch(() => {})
  currentIdx.value = idx
  currentTime.value = 0
  duration.value = 0
  loadCoverForTrack(track)
}

function togglePlay() {
  if (!audio) return
  if (playing.value) {
    audio.pause()
    return
  }
  if (currentIdx.value < 0 && tracks.value.length > 0) {
    playAt(0)
    return
  }
  audio.play().catch(() => {})
}

function prevTrack() {
  if (!tracks.value.length) return
  if (audio && audio.currentTime > 3) {
    audio.currentTime = 0
    return
  }
  const next = (currentIdx.value - 1 + tracks.value.length) % tracks.value.length
  playAt(next)
}

function nextTrack() {
  if (!tracks.value.length) return
  const next = (currentIdx.value + 1) % tracks.value.length
  playAt(next)
}

function seek(ratio) {
  if (!audio || !Number.isFinite(audio.duration)) return
  audio.currentTime = Math.max(0, Math.min(audio.duration, audio.duration * ratio))
}

function removeTrack(idx) {
  const removed = tracks.value[idx]
  tracks.value = tracks.value.filter((_, i) => i !== idx)
  if (!removed) return

  if (idx === currentIdx.value) {
    audio?.pause()
    if (tracks.value.length === 0) {
      currentIdx.value = -1
      currentTime.value = 0
      duration.value = 0
      playing.value = false
      return
    }
    const newIdx = Math.min(idx, tracks.value.length - 1)
    playAt(newIdx)
  } else if (idx < currentIdx.value) {
    currentIdx.value -= 1
  }
}

function onDragOver() {
  dragOver.value = true
}

function onDragLeave() {
  dragOver.value = false
}

async function onDrop(event) {
  dragOver.value = false
  const files = [...event.dataTransfer.files].map((file) => file.path).filter(Boolean)
  await addPaths(files)
}

function drawSpectrum() {
  const canvas = canvasRef.value
  if (!canvas) return
  const ctx2d = canvas.getContext('2d')
  if (!ctx2d) return

  const wrap = canvas.parentElement
  const dpr = window.devicePixelRatio || 1
  const cssW = Math.max(1, Math.round(wrap.clientWidth))
  const cssH = Math.max(1, Math.round(wrap.clientHeight))
  const targetW = Math.max(1, Math.round(cssW * dpr))
  const targetH = Math.max(1, Math.round(cssH * dpr))
  if (canvas.width !== targetW || canvas.height !== targetH) {
    canvas.width = targetW
    canvas.height = targetH
    canvas.style.width = `${cssW}px`
    canvas.style.height = `${cssH}px`
  }

  ctx2d.setTransform(1, 0, 0, 1, 0, 0)
  ctx2d.scale(dpr, dpr)
  ctx2d.clearRect(0, 0, cssW, cssH)
  ctx2d.fillStyle = '#000'
  ctx2d.fillRect(0, 0, cssW, cssH)

  const barW = 5
  const gap = 2
  const step = barW + gap
  const bars = Math.max(10, Math.floor(cssW / step))

  let freq = null
  if (analyser) {
    freq = new Uint8Array(analyser.frequencyBinCount)
    analyser.getByteFrequencyData(freq)
  }

  let active = 0
  for (let i = 0; i < bars; i++) {
    const x = i * step
    let amp = 0

    if (freq) {
      const pos = i / bars
      const lo = Math.floor(Math.pow(pos, 1.25) * (freq.length - 1))
      const hi = Math.max(lo + 1, Math.floor(Math.pow((i + 1) / bars, 1.25) * (freq.length - 1)))
      let sum = 0
      for (let b = lo; b <= hi && b < freq.length; b++) sum += freq[b]
      const avg = sum / Math.max(1, hi - lo + 1)
      amp = Math.pow(Math.min(1, avg / 255), 0.85)
    }

    const h = Math.max(playing.value ? 2 : 0, Math.floor(amp * cssH * 0.95))
    if (h > 2) active += 1

    const grad = ctx2d.createLinearGradient(0, cssH - h, 0, cssH)
    grad.addColorStop(0, '#00ff41')
    grad.addColorStop(0.45, '#00aa33')
    grad.addColorStop(1, '#003311')
    ctx2d.fillStyle = grad
    ctx2d.fillRect(x, cssH - h, barW, h)
  }

  if (playing.value && active === 0) {
    const pulse = Math.floor((Date.now() / 120) % bars)
    for (let i = 0; i < Math.min(10, bars); i++) {
      const p = (pulse + i) % bars
      const x = p * step
      const h = Math.max(6, Math.floor(cssH * (0.1 + i * 0.02)))
      ctx2d.fillStyle = 'rgba(0,255,65,0.28)'
      ctx2d.fillRect(x, cssH - h, barW, h)
    }
  }

  rafId = requestAnimationFrame(drawSpectrum)
}

onMounted(() => {
  audio = new Audio()
  audio.preload = 'auto'
  audio.volume = volume.value

  const Ctx = window.AudioContext || window.webkitAudioContext
  if (Ctx) {
    audioCtx = new Ctx()
    analyser = audioCtx.createAnalyser()
    analyser.fftSize = 1024
    analyser.smoothingTimeConstant = 0.56
    analyser.minDecibels = -90
    analyser.maxDecibels = -10
    sourceNode = audioCtx.createMediaElementSource(audio)
    sourceNode.connect(analyser)
    analyser.connect(audioCtx.destination)
  }

  audio.addEventListener('timeupdate', () => { currentTime.value = audio.currentTime })
  audio.addEventListener('loadedmetadata', () => {
    duration.value = Number.isFinite(audio.duration) ? audio.duration : 0
    const idx = currentIdx.value
    if (idx >= 0 && tracks.value[idx]) {
      tracks.value[idx].duration = duration.value
    }
  })
  audio.addEventListener('play', () => { playing.value = true })
  audio.addEventListener('pause', () => { playing.value = false })
  audio.addEventListener('ended', () => { nextTrack() })

  drawSpectrum()
})

onBeforeUnmount(() => {
  if (rafId) cancelAnimationFrame(rafId)
  if (sourceNode) sourceNode.disconnect()
  if (analyser) analyser.disconnect()
  if (audioCtx) audioCtx.close()
  if (audio) audio.pause()
})

watch(volume, (v) => {
  if (!audio) return
  audio.volume = Math.max(0, Math.min(1, v))
})

watch(muted, (m) => {
  if (!audio) return
  audio.muted = !!m
})

watch(
  settings,
  (value) => {
    localStorage.setItem(SETTINGS_KEY, JSON.stringify(value))
  },
  { deep: true }
)

watch(
  () => settings.value.compactMode,
  async (value) => {
    await window.electronAPI.setCompactMode?.(value)
  },
  { immediate: true }
)

watch(currentTrack, (track) => {
  if (track) loadCoverForTrack(track)
})

const progressRatio = computed(() => {
  if (!duration.value || duration.value <= 0) return 0
  return Math.max(0, Math.min(1, currentTime.value / duration.value))
})
</script>

<template>
  <div
    class="app vue-player"
    :class="{ 'app--compact': compact, 'app--dragover': dragOver }"
    @dragover.prevent="onDragOver"
    @dragleave.prevent="onDragLeave"
    @drop.prevent="onDrop"
  >
    <div class="titlebar">
      <span class="titlebar__logo">RETROAMP</span>
      <div class="titlebar__menu">
        <button @click="openFiles">[ФАЙЛЫ]</button>
        <button @click="openFolder">[ПАПКА]</button>
        <button @click="importM3U">[M3U I]</button>
        <button @click="exportM3U">[M3U E]</button>
        <button @click="openSettings">[НАСТРОЙКИ]</button>
      </div>
      <span class="titlebar__track">{{ currentTrack ? `♪ ${currentTrack.title} — ${currentTrack.artist || 'Unknown artist'}` : 'RetroAmp Vue Player' }}</span>
      <div class="titlebar__wctrl">
        <button class="wctrl" @click="window.electronAPI.minimize()">─</button>
        <button class="wctrl" @click="window.electronAPI.maximize()">□</button>
        <button class="wctrl wctrl--close" @click="window.electronAPI.close()">✕</button>
      </div>
    </div>

    <div class="main-area">
      <div class="playlist" v-if="!compact">
        <div class="playlist__header">
          <span class="playlist__title">ПЛЕЙЛИСТ — {{ tracks.length }}</span>
        </div>
        <div class="playlist__list">
          <div
            v-for="(track, idx) in tracks"
            :key="track.id"
            class="playlist__item"
            :class="{ 'playlist__item--active': idx === currentIdx }"
            @click="playAt(idx)"
          >
            <span class="playlist__item-num">{{ String(idx + 1).padStart(2, '0') }}.</span>
            <span class="playlist__item-name">{{ track.title }}{{ track.artist ? ` — ${track.artist}` : '' }}</span>
            <span class="playlist__item-dur">{{ track.duration > 0 ? fmtTime(track.duration) : '' }}</span>
            <button class="playlist__item-del" @click.stop="removeTrack(idx)">✕</button>
          </div>
        </div>
      </div>

      <div class="right-panel">
        <div class="spectrum-wrap" @contextmenu.prevent="() => {}">
          <canvas ref="canvasRef" class="spectrum-canvas" />
        </div>

        <div class="track-meta" v-if="settings.showCover || currentTrack">
          <div class="track-meta__cover-wrap">
            <img v-if="currentTrack?.cover" :src="currentTrack.cover" alt="Album cover" class="track-meta__cover" />
            <div v-else class="track-meta__cover track-meta__cover--fallback">NO COVER</div>
          </div>

          <div class="track-info">
            <span class="track-info__label">NOW PLAYING</span>
            <span class="track-info__title">{{ currentTrack ? currentTrack.title : 'No track loaded' }}</span>
            <div class="track-info__meta" v-if="currentTrack">
              <span class="track-info__sub">Artist: {{ currentTrack.artist || 'Unknown artist' }}</span>
              <span class="track-info__sub">Album: {{ currentTrack.album || 'Unknown album' }}<span v-if="currentTrack.year"> ({{ currentTrack.year }})</span></span>
            </div>
            <span class="track-info__sub" v-else>Open files/folder to start playback.</span>
          </div>
        </div>
      </div>
    </div>

    <div class="controls">
      <div class="controls__seekrow">
        <span class="controls__time">{{ fmtTime(currentTime) }}</span>
        <input
          class="controls__seek"
          type="range"
          min="0"
          max="1"
          step="0.0001"
          :value="progressRatio"
          @input="seek(parseFloat($event.target.value))"
        />
        <span class="controls__time controls__time--right">{{ fmtTime(duration) }}</span>
      </div>

      <div class="controls__row">
        <div class="controls__transport">
          <button class="ctrl" @click="prevTrack">|◄◄</button>
          <button class="ctrl ctrl--play" @click="togglePlay">{{ playing ? '‖‖' : ' ▶ ' }}</button>
          <button class="ctrl" @click="nextTrack">▶▶|</button>
        </div>

        <div class="controls__spacer" />

        <div class="controls__vol">
          <button class="ctrl ctrl--icon" @click="muted = !muted">{{ muted ? '🔇' : '🔊' }}</button>
          <input
            class="controls__volbar"
            type="range"
            min="0"
            max="1"
            step="0.01"
            :value="muted ? 0 : volume"
            @input="volume = parseFloat($event.target.value)"
          />
          <span class="controls__volpct">{{ Math.round(volume * 100) }}%</span>
        </div>
      </div>
    </div>

    <div v-if="showSettings" class="settings" @click.self="closeSettings">
      <div class="settings__panel">
        <div class="settings__head">
          <span>НАСТРОЙКИ</span>
          <button @click="closeSettings">✕</button>
        </div>
        <label class="settings__row settings__row--check">
          <input type="checkbox" v-model="settings.compactMode" />
          <span>Компактный режим</span>
        </label>
        <label class="settings__row settings__row--check">
          <input type="checkbox" v-model="settings.showCover" />
          <span>Показывать обложку</span>
        </label>
        <label class="settings__row settings__row--check">
          <input type="checkbox" v-model="settings.autoPlayOnAdd" />
          <span>Автозапуск при добавлении</span>
        </label>
        <label class="settings__row">
          <span>Интенсивность визуализации</span>
          <input type="range" min="0.6" max="1.6" step="0.05" v-model.number="settings.vizIntensity" />
        </label>
        <div class="settings__footer">
          <button @click="closeSettings">ОК</button>
        </div>
      </div>
    </div>
  </div>
</template>
